language: cpp

sudo: required

dist: trusty

compiler:
  - clang
  - gcc

os:
  - linux
   
before_install:
  - sudo apt-get update
  - sudo apt-get install -y libgsl-dev libarmadillo-dev libboost-all-dev
  - git submodule update --init --recursive
