language: cpp

sudo: required

dist: trusty

compiler:
  - clang
  - gcc

os:
  - linux
   
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libgsl0-dev libarmadillo-dev libboost-all-dev
  - git submodule update --init --recursive

script:
  - mkdir build
  - cd build
  - cmake ..
  - make
