name: Lint

on: [push]


jobs:
  lint:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: '3.6'
        architecture: 'x64'

    - name: Install cpplint
      run: pip install cpplint

    - name: Lint
      run: ./lint.sh
