name: Python Tests

on: [push]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true
    - uses: actions/setup-python@v1
    - name: Install dependencies
      run: sudo ./install_dependencies.sh
    - name: pip install
      run: pip install -e .[test]
    - name: Pytest E2E
      run: pytest tests/e2e
    - name: Pytest Regression
      run: pytest tests/regression --benchmark-json benchmark.json
    - name: Store benchmark result
      uses: rhysd/github-action-benchmark@v1
      with:
        name: Python Benchmark with pytest-benchmark
        tool: 'pytest'
        output-file-path: benchmark.json
        github-token: ${{ secrets.GITHUB_TOKEN }}
        auto-push: true
        # Show alert on detecting possible performance regression
        alert-threshold: '50%'
        fail-on-alert: true
